using System.Text.Json;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Prognosis;
using Prognosis.DependencyInjection;

// ─────────────────────────────────────────────────────────────────────
// Build the host with Prognosis health graph wired via DI.
// ─────────────────────────────────────────────────────────────────────

var builder = Host.CreateApplicationBuilder(args);

// Register the third-party service we'll wrap with a health probe.
builder.Services.AddSingleton<ThirdPartyEmailClient>();

builder.Services.AddPrognosis(health =>
{
    // Auto-generated by Prognosis.Generators — discovers all classes with
    // public HealthNode properties and wires [DependsOn] edges.
    health.AddDiscoveredNodes();

    // Wrap a third-party service you don't own with a health probe.
    // Name defaults to typeof(ThirdPartyEmailClient).Name when omitted.
    health.AddNode("EmailProvider")
        .WithHealthProbe<ThirdPartyEmailClient>(client => client.IsConnected
            ? HealthStatus.Healthy
            : HealthEvaluation.Unhealthy("SMTP connection refused"));

    // Define aggregation nodes.
    // The string literal in AddNode is the definition site —
    // the generator reads it and emits a HealthNames constant.
    // Reference sites (DependsOn, MarkAsRoot) use the generated constants.
    health.AddNode("NotificationSystem")
        .DependsOn(HealthNames.MessageQueueService, Importance.Required)
        .DependsOn(HealthNames.EmailProvider, Importance.Optional);

    health.AddNode("Application")
        .DependsOn<AuthService>(Importance.Required)
        .DependsOn(HealthNames.NotificationSystem, Importance.Important);

    // Designate the root — required when multiple top-level nodes exist.
    health.MarkAsRoot(HealthNames.Application);

    // Register HealthMonitor as a hosted service (polls every 2 seconds).
    health.UseMonitor(TimeSpan.FromSeconds(2));
});

var host = builder.Build();

// ─────────────────────────────────────────────────────────────────────
// Resolve the health graph and inspect it.
// ─────────────────────────────────────────────────────────────────────

var graph = host.Services.GetRequiredService<HealthGraph>();
var monitor = host.Services.GetRequiredService<HealthMonitor>();
var jsonOptions = new JsonSerializerOptions { WriteIndented = true };

Console.WriteLine("=== Initial health report ===");
var report = graph.GetReport();
Console.WriteLine(JsonSerializer.Serialize(report, jsonOptions));
Console.WriteLine();

// ─────────────────────────────────────────────────────────────────────
// Subscribe to report changes and simulate failures.
// ─────────────────────────────────────────────────────────────────────

Console.WriteLine("=== Subscribing to HealthMonitor.ReportChanged ===");
using var subscription = monitor.ReportChanged.Subscribe(new ReportObserver());

// Initial poll to establish baseline.
monitor.Poll();
Console.WriteLine();

// Simulate a database failure.
var database = host.Services.GetRequiredService<DatabaseService>();
Console.WriteLine("  Taking database offline...");
database.IsConnected = false;
monitor.Poll();
Console.WriteLine();

// Restore it.
Console.WriteLine("  Restoring database...");
database.IsConnected = true;
monitor.Poll();
Console.WriteLine();

// Simulate an email provider failure (optional dependency — no effect on Application).
var emailClient = host.Services.GetRequiredService<ThirdPartyEmailClient>();
Console.WriteLine("  Taking email provider offline (optional — no effect on Application)...");
emailClient.IsConnected = false;
monitor.Poll();
Console.WriteLine();

// Show the diff API.
Console.WriteLine("=== Report diffing ===");
var before = graph.GetReport();
emailClient.IsConnected = true;
database.IsConnected = false;
graph.RefreshAll();
var after = graph.GetReport();

var changes = before.DiffTo(after);
foreach (var change in changes)
{
    Console.WriteLine($"  {change.Name}: {change.Previous} → {change.Current} ({change.Reason})");
}
Console.WriteLine();

// ─────────────────────────────────────────────────────────────────────
// Look up services by name.
// ─────────────────────────────────────────────────────────────────────

Console.WriteLine("=== HealthGraph lookup ===");
foreach (var node in graph.Nodes)
{
    Console.WriteLine($"  {node}");
}
Console.WriteLine();

// Type-safe lookup — uses typeof(AuthService).Name as the key.
if (graph.TryGetNode<AuthService>(out var auth))
{
    Console.WriteLine($"  AuthService has {auth.Dependencies.Count} dependencies");
}

// ─────────────────────────────────────────────────────────────────────
// Multiple roots — shared nodes, separate graphs.
//
// (Commented out to avoid conflicts with rich reporting example services)
// A second AddPrognosis call creates a separate configuration with
// multiple MarkAsRoot calls. Each root produces a separate HealthGraph
// that shares the same underlying HealthNode instances.
// ─────────────────────────────────────────────────────────────────────

/*
Console.WriteLine();
Console.WriteLine("=== Multi-root health graphs ===");

var multiBuilder = Host.CreateApplicationBuilder(args);
multiBuilder.Services.AddSingleton<ThirdPartyEmailClient>();

multiBuilder.Services.AddPrognosis(health =>
{
    health.AddDiscoveredNodes();

    health.AddNode("EmailProvider")
        .WithHealthProbe<ThirdPartyEmailClient>(client => client.IsConnected
            ? HealthStatus.Healthy
            : HealthEvaluation.Unhealthy("SMTP refused"));

    health.AddNode("NotificationSystem")
        .DependsOn(HealthNames.MessageQueueService, Importance.Required)
        .DependsOn(HealthNames.EmailProvider, Importance.Optional);

    // Two different views of the same service pool.
    health.AddNode(nameof(OpsView))
        .DependsOn<DatabaseService>(Importance.Required)
        .DependsOn<CacheService>(Importance.Required)
        .DependsOn(HealthNames.NotificationSystem, Importance.Important);

    health.AddNode(nameof(CustomerView))
        .DependsOn<AuthService>(Importance.Required);

    // Each call produces a separate HealthGraph. Because MarkAsRoot<T>()
    // is used, both keyed and generic resolutions are available.
    health.MarkAsRoot<OpsView>();
    health.MarkAsRoot<CustomerView>();
});

var multiHost = multiBuilder.Build();
var sp = multiHost.Services;

// Keyed resolution — use the root name as the key.
var opsGraphKeyed = sp.GetRequiredKeyedService<HealthGraph>(nameof(OpsView));
var custGraphKeyed = sp.GetRequiredKeyedService<HealthGraph>(nameof(CustomerView));

Console.WriteLine($"  Ops root (keyed):      {opsGraphKeyed.Root.Name} ({opsGraphKeyed.Nodes.Count()} nodes)");
Console.WriteLine($"  Customer root (keyed): {custGraphKeyed.Root.Name} ({custGraphKeyed.Nodes.Count()} nodes)");

// Generic resolution — works on any DI container without keyed support.
var opsGraphTyped = sp.GetRequiredService<HealthGraph<OpsView>>();
var custGraphTyped = sp.GetRequiredService<HealthGraph<CustomerView>>();

Console.WriteLine($"  Ops root (typed):      {opsGraphTyped.Root.Name}");
Console.WriteLine($"  Customer root (typed): {custGraphTyped.Root.Name}");

// Verify that nodes are shared across the two graphs.
opsGraphKeyed.TryGetNode(HealthNames.Database, out var opsDb);
custGraphKeyed.TryGetNode(HealthNames.Database, out var custDb);
Console.WriteLine($"  Shared Database node:  {ReferenceEquals(opsDb, custDb)}");
Console.WriteLine();
*/

// ─────────────────────────────────────────────────────────────────────
// Rich reporting — correlating health snapshots with operational metadata.
//
// Tags provide the correlation key. Services that want to expose
// operational details (config, device IDs, etc.) implement IServiceMetadata.
// The enrichment extension method joins health snapshots with metadata.
// ─────────────────────────────────────────────────────────────────────

Console.WriteLine("=== Rich reporting with metadata enrichment ===");

var richBuilder = Host.CreateApplicationBuilder(args);

// Register services with metadata.
richBuilder.Services.AddSingleton<MetadataAwareDatabaseService>();
richBuilder.Services.AddSingleton<MetadataAwareCacheService>();

// Register metadata providers.
richBuilder.Services.AddSingleton<IServiceMetadata>(sp =>
    sp.GetRequiredService<MetadataAwareDatabaseService>());
richBuilder.Services.AddSingleton<IServiceMetadata>(sp =>
    sp.GetRequiredService<MetadataAwareCacheService>());

richBuilder.Services.AddPrognosis(health =>
{
    // Service nodes expose tags for correlation.
    health.AddServiceNode<MetadataAwareDatabaseService>(svc => svc.HealthNode);
    health.AddServiceNode<MetadataAwareCacheService>(svc => svc.HealthNode);

    health.AddNode("RichApp")
        .DependsOn(nameof(MetadataAwareDatabaseService), Importance.Required)
        .DependsOn(nameof(MetadataAwareCacheService), Importance.Important);

    health.MarkAsRoot("RichApp");
});

var richHost = richBuilder.Build();
var richGraph = richHost.Services.GetRequiredService<HealthGraph>();

var basicReport = richGraph.GetReport();
Console.WriteLine("  Basic report (no metadata):");
foreach (var snapshot in basicReport.Nodes.Take(2))
{
    Console.WriteLine($"    {snapshot.Name}: {snapshot.Status}");
    if (snapshot.Tags is not null)
    {
        foreach (var tag in snapshot.Tags)
            Console.WriteLine($"      tag: {tag.Key}={tag.Value}");
    }
}
Console.WriteLine();

// Enrich with operational metadata from IServiceMetadata providers.
var richReport = basicReport.EnrichWithMetadata(richHost.Services);
Console.WriteLine("  Rich report (with metadata):");
foreach (var snapshot in richReport.Nodes.Take(2))
{
    Console.WriteLine($"    {snapshot.Name}: {snapshot.Status}");
    if (snapshot.Tags is not null)
    {
        foreach (var tag in snapshot.Tags)
            Console.WriteLine($"      tag: {tag.Key}={tag.Value}");
    }
    if (snapshot.Metadata is not null)
    {
        foreach (var entry in snapshot.Metadata)
            Console.WriteLine($"      meta: {entry.Key}={entry.Value}");
    }
}
Console.WriteLine();

// ─────────────────────────────────────────────────────────────────────
// Example service classes
// ─────────────────────────────────────────────────────────────────────

/// <summary>
/// A service you own — expose a <see cref="HealthNode"/> property.
/// The generator discovers this automatically via AddDiscoveredNodes().
/// </summary>
class DatabaseService
{
    public HealthNode HealthNode { get; }

    public DatabaseService()
    {
        HealthNode = HealthNode.Create("Database").WithHealthProbe(
            () => IsConnected
                ? HealthStatus.Healthy
                : HealthEvaluation.Unhealthy("Connection lost"));
    }

    public bool IsConnected { get; set; } = true;
}

/// <summary>Another service you own, same pattern.</summary>
class CacheService
{
    public HealthNode HealthNode { get; }

    public CacheService()
    {
        HealthNode = HealthNode.Create("Cache").WithHealthProbe(
            () => IsConnected
                ? HealthStatus.Healthy
                : HealthEvaluation.Unhealthy("Redis timeout"));
    }

    public bool IsConnected { get; set; } = true;
}

/// <summary>
/// A service that declares its dependencies via property-level attributes.
/// The generator reads these and emits edge wiring in AddDiscoveredNodes().
/// </summary>
class AuthService
{
    [DependsOn("Database", Importance.Required)]
    [DependsOn("Cache", Importance.Important)]
    public HealthNode HealthNode { get; } = HealthNode.Create("AuthService");
}

/// <summary>Always-healthy placeholder for demo purposes.</summary>
class MessageQueueService
{
    public HealthNode HealthNode { get; } = HealthNode.Create(nameof(MessageQueueService));
}

/// <summary>
/// A third-party class you cannot modify.
/// Wrapped via <c>AddProbe&lt;T&gt;</c> in the builder above.
/// </summary>
class ThirdPartyEmailClient
{
    public bool IsConnected { get; set; } = true;
}

/// <summary>Minimal observer for the demo.</summary>
class ReportObserver : IObserver<HealthReport>
{
    public void OnNext(HealthReport value) =>
        Console.WriteLine($"    >> Report changed: {value.Nodes.Count} nodes");
    public void OnError(Exception error) { }
    public void OnCompleted() { }
}

/// <summary>Marker types for multi-root graph resolution.</summary>
class OpsView;
class CustomerView;

// ─────────────────────────────────────────────────────────────────────
// Metadata-aware service implementations for rich reporting example
// ─────────────────────────────────────────────────────────────────────

/// <summary>
/// A service that exposes both a HealthNode (for health status) and
/// IServiceMetadata (for operational details like connection strings,
/// device IDs, configuration, etc.).
/// </summary>
class MetadataAwareDatabaseService : IServiceMetadata
{
    public HealthNode HealthNode { get; }

    public MetadataAwareDatabaseService()
    {
        HealthNode = HealthNode.Create(nameof(MetadataAwareDatabaseService))
            .WithHealthProbe(() => HealthStatus.Healthy)
            .WithTags(new Dictionary<string, string>
            {
                ["env"] = "production",
                ["owner"] = "platform-team",
                ["tier"] = "critical"
            });
    }

    // IServiceMetadata implementation — operational details.
    public string Name => nameof(MetadataAwareDatabaseService);
    public IReadOnlyDictionary<string, object> Details => new Dictionary<string, object>
    {
        ["connection_string"] = "Server=prod-db-01;Database=app",
        ["pool_size"] = 50,
        ["timeout_seconds"] = 30,
        ["version"] = "PostgreSQL 15.2"
    };
}

class MetadataAwareCacheService : IServiceMetadata
{
    public HealthNode HealthNode { get; }

    public MetadataAwareCacheService()
    {
        HealthNode = HealthNode.Create(nameof(MetadataAwareCacheService))
            .WithHealthProbe(() => HealthStatus.Healthy)
            .WithTags(new Dictionary<string, string>
            {
                ["env"] = "production",
                ["region"] = "us-east-1"
            });
    }

    public string Name => nameof(MetadataAwareCacheService);
    public IReadOnlyDictionary<string, object> Details => new Dictionary<string, object>
    {
        ["endpoint"] = "redis-cluster-01.amazonaws.com:6379",
        ["cluster_mode"] = true,
        ["max_connections"] = 100
    };
}

// ─────────────────────────────────────────────────────────────────────
// Enrichment infrastructure (your code, not part of Prognosis core)
// ─────────────────────────────────────────────────────────────────────

/// <summary>
/// Optional interface for services that want to expose operational metadata
/// in rich health reports. Tags on HealthNode provide the correlation key;
/// this interface provides the "juicy details."
/// </summary>
interface IServiceMetadata
{
    string Name { get; }
    IReadOnlyDictionary<string, object> Details { get; }
}

/// <summary>
/// A health report enriched with operational metadata from IServiceMetadata.
/// </summary>
record RichHealthReport(
    RichHealthSnapshot Root,
    IReadOnlyList<RichHealthSnapshot> Nodes);

/// <summary>
/// A health snapshot enriched with operational metadata.
/// </summary>
record RichHealthSnapshot(
    string Name,
    HealthStatus Status,
    string? Reason,
    IReadOnlyDictionary<string, string>? Tags,
    IReadOnlyDictionary<string, object>? Metadata);

/// <summary>
/// Extension method that joins HealthReport with IServiceMetadata providers
/// registered in DI. Correlation is by node name; you could also match on tags.
/// </summary>
static class HealthReportEnrichmentExtensions
{
    public static RichHealthReport EnrichWithMetadata(
        this HealthReport report,
        IServiceProvider services)
    {
        // Build a lookup of metadata by service name.
        var metadataByName = services.GetServices<IServiceMetadata>()
            .ToDictionary(m => m.Name, m => m.Details);

        var enrichedNodes = new List<RichHealthSnapshot>();
        foreach (var snapshot in report.Nodes)
        {
            metadataByName.TryGetValue(snapshot.Name, out var metadata);
            enrichedNodes.Add(new RichHealthSnapshot(
                snapshot.Name,
                snapshot.Status,
                snapshot.Reason,
                snapshot.Tags,
                metadata));
        }

        var rootMeta = metadataByName.GetValueOrDefault(report.Root.Name);
        var enrichedRoot = new RichHealthSnapshot(
            report.Root.Name,
            report.Root.Status,
            report.Root.Reason,
            report.Root.Tags,
            rootMeta);

        return new RichHealthReport(enrichedRoot, enrichedNodes);
    }
}
