using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Prognosis.Generators;

/// <summary>
/// Incremental source generator that scans for classes with public
/// <c>HealthNode</c> properties, reads <c>[DependsOn]</c> attributes
/// on those properties, and emits an <c>AddDiscoveredNodes()</c>
/// extension method on <c>PrognosisBuilder</c>.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class ServiceNodeDiscoveryGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var nodes = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsHealthNodePropertyCandidate(node),
                transform: static (ctx, _) => ExtractServiceNode(ctx))
            .Where(static info => info is not null)
            .Collect();

        var nodesWithCompilation = nodes.Combine(context.CompilationProvider);

        context.RegisterSourceOutput(nodesWithCompilation, static (spc, pair) =>
        {
            var (collected, compilation) = pair;

            // Only emit AddDiscoveredNodes when PrognosisBuilder is referenceable.
            if (compilation.GetTypeByMetadataName("Prognosis.DependencyInjection.PrognosisBuilder") is null)
                return;

            var entries = collected
                .Where(e => e is not null)
                .Cast<ServiceNodeEntry>()
                .ToImmutableArray();

            if (entries.Length == 0)
                return;

            spc.AddSource(
                "AddDiscoveredNodes.g.cs",
                SourceText.From(GenerateExtension(entries), Encoding.UTF8));
        });
    }

    private static bool IsHealthNodePropertyCandidate(SyntaxNode node)
    {
        return node is PropertyDeclarationSyntax prop
            && prop.Type is IdentifierNameSyntax { Identifier.Text: "HealthNode" }
               or QualifiedNameSyntax { Right.Identifier.Text: "HealthNode" };
    }

    private static ServiceNodeEntry? ExtractServiceNode(GeneratorSyntaxContext ctx)
    {
        var prop = (PropertyDeclarationSyntax)ctx.Node;

        if (ctx.SemanticModel.GetDeclaredSymbol(prop) is not IPropertySymbol propSymbol)
            return null;

        if (propSymbol.Type is not { Name: "HealthNode" }
            || propSymbol.Type.ContainingNamespace?.ToString() != "Prognosis")
            return null;

        if (propSymbol.DeclaredAccessibility != Accessibility.Public)
            return null;

        var containingType = propSymbol.ContainingType;
        if (containingType is null || containingType.IsAbstract || containingType.IsStatic)
            return null;

        var fullTypeName = containingType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var propertyName = propSymbol.Name;

        var deps = ImmutableArray.CreateBuilder<DependencyEntry>();
        foreach (var attr in propSymbol.GetAttributes())
        {
            if (attr.AttributeClass is not { Name: "DependsOnAttribute" }
                || attr.AttributeClass.ContainingNamespace?.ToString() != "Prognosis.DependencyInjection")
                continue;

            if (attr.ConstructorArguments.Length < 1)
                continue;

            var depName = attr.ConstructorArguments[0].Value as string;
            if (string.IsNullOrEmpty(depName))
                continue;

            var importance = "Importance.Required";
            if (attr.ConstructorArguments.Length >= 2
                && attr.ConstructorArguments[1].Value is int impVal)
            {
                importance = impVal switch
                {
                    0 => "Importance.Required",
                    1 => "Importance.Important",
                    2 => "Importance.Optional",
                    3 => "Importance.Resilient",
                    _ => "Importance.Required",
                };
            }

            deps.Add(new DependencyEntry(depName!, importance));
        }

        return new ServiceNodeEntry(fullTypeName, propertyName, deps.ToImmutable());
    }

    private static string GenerateExtension(ImmutableArray<ServiceNodeEntry> entries)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace Prognosis.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Auto-generated extension that registers all discovered service nodes");
        sb.AppendLine("/// (classes with public <see cref=\"Prognosis.HealthNode\"/> properties)");
        sb.AppendLine("/// and their <c>[DependsOn]</c>-declared edges.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class PrognosisBuilderDiscoveryExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Registers all <see cref=\"Prognosis.HealthNode\"/> properties discovered");
        sb.AppendLine("    /// in this compilation via <see cref=\"PrognosisBuilder.AddServiceNode{TService}\"/>.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static PrognosisBuilder AddDiscoveredNodes(this PrognosisBuilder builder)");
        sb.AppendLine("    {");

        foreach (var entry in entries)
        {
            if (entry.Dependencies.Length == 0)
            {
                sb.AppendLine($"        builder.AddServiceNode<{entry.FullTypeName}>(svc => svc.{entry.PropertyName});");
            }
            else
            {
                sb.AppendLine($"        builder.AddServiceNode<{entry.FullTypeName}>(svc => svc.{entry.PropertyName}, deps =>");
                sb.AppendLine("        {");
                foreach (var dep in entry.Dependencies)
                {
                    sb.AppendLine($"            deps.DependsOn(\"{EscapeString(dep.NodeName)}\", {dep.Importance});");
                }
                sb.AppendLine("        });");
            }
        }

        sb.AppendLine("        return builder;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string EscapeString(string value) =>
        value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private sealed class ServiceNodeEntry
    {
        public string FullTypeName { get; }
        public string PropertyName { get; }
        public ImmutableArray<DependencyEntry> Dependencies { get; }

        public ServiceNodeEntry(string fullTypeName, string propertyName, ImmutableArray<DependencyEntry> dependencies)
        {
            FullTypeName = fullTypeName;
            PropertyName = propertyName;
            Dependencies = dependencies;
        }
    }

    private sealed class DependencyEntry
    {
        public string NodeName { get; }
        public string Importance { get; }

        public DependencyEntry(string nodeName, string importance)
        {
            NodeName = nodeName;
            Importance = importance;
        }
    }
}
