using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Testing;
using Microsoft.CodeAnalysis.Testing;
using Prognosis.Generators;
using Xunit;

namespace Prognosis.Generators.Tests;

public class HealthNodeNameCollectorTests
{
    [Fact]
    public async Task CreateDelegate_SingleNode_GeneratesHealthNames()
    {
        var source = """
            using Prognosis;

            class Setup
            {
                void Configure()
                {
                    var node = HealthNode.CreateDelegate("Database");
                }
            }
            """;

        var expected = """
            // <auto-generated />
            #nullable enable

            namespace Prognosis;

            /// <summary>
            /// Auto-generated constants for every health node name discovered in this
            /// compilation via <c>HealthNode.CreateDelegate</c>, <c>CreateComposite</c>,
            /// <c>PrognosisBuilder.AddComposite</c>, and <c>AddDelegate</c> calls.
            /// Use these constants in place of string literals for refactoring safety,
            /// autocomplete, and find-all-references support.
            /// </summary>
            public static class HealthNames
            {
                /// <summary>Node name: <c>"Database"</c></summary>
                public const string Database = "Database";
            }

            """;

        await RunGeneratorTest(source, ("HealthNames.g.cs", expected));
    }

    [Fact]
    public async Task CreateDelegate_And_CreateComposite_CollectsBoth()
    {
        var source = """
            using Prognosis;

            class Setup
            {
                void Configure()
                {
                    var a = HealthNode.CreateDelegate("Cache");
                    var b = HealthNode.CreateComposite("Application");
                }
            }
            """;

        var generated = await RunGeneratorAndGetSource(source);

        Assert.Contains("public const string Application = \"Application\";", generated);
        Assert.Contains("public const string Cache = \"Cache\";", generated);
    }

    [Fact]
    public async Task DottedNames_SanitizedToUnderscores()
    {
        var source = """
            using Prognosis;

            class Setup
            {
                void Configure()
                {
                    var a = HealthNode.CreateDelegate("Database.Connection");
                    var b = HealthNode.CreateDelegate("Database.Latency");
                }
            }
            """;

        var generated = await RunGeneratorAndGetSource(source);

        Assert.Contains("public const string Database_Connection = \"Database.Connection\";", generated);
        Assert.Contains("public const string Database_Latency = \"Database.Latency\";", generated);
    }

    [Fact]
    public async Task DuplicateNames_EmittedOnce()
    {
        var source = """
            using Prognosis;

            class Setup
            {
                void Configure()
                {
                    var a = HealthNode.CreateDelegate("Cache");
                    var b = HealthNode.CreateDelegate("Cache");
                }
            }
            """;

        var generated = await RunGeneratorAndGetSource(source);

        var count = generated.Split(new[] { "public const string Cache" }, StringSplitOptions.None).Length - 1;
        Assert.Equal(1, count);
    }

    [Fact]
    public async Task ConstStringArg_Extracted()
    {
        var source = """
            using Prognosis;

            class Setup
            {
                const string Name = "MyService";
                void Configure()
                {
                    var node = HealthNode.CreateDelegate(Name);
                }
            }
            """;

        var generated = await RunGeneratorAndGetSource(source);

        Assert.Contains("public const string MyService = \"MyService\";", generated);
    }

    [Fact]
    public async Task NoFactoryCalls_NoOutput()
    {
        var source = """
            class Empty
            {
            }
            """;

        var driver = CreateDriver(source);
        var result = driver.GetRunResult();

        Assert.Empty(result.GeneratedTrees);
    }

    [Fact]
    public void SanitizeFieldName_Dots_Become_Underscores()
    {
        Assert.Equal("Database_Connection", HealthNodeNameCollector.SanitizeFieldName("Database.Connection"));
    }

    [Fact]
    public void SanitizeFieldName_LeadingDigit_Prefixed()
    {
        Assert.Equal("_3rdParty", HealthNodeNameCollector.SanitizeFieldName("3rdParty"));
    }

    [Fact]
    public void SanitizeFieldName_PlainName_Unchanged()
    {
        Assert.Equal("Cache", HealthNodeNameCollector.SanitizeFieldName("Cache"));
    }

    [Fact]
    public async Task AddComposite_StringArg_CollectedIntoHealthNames()
    {
        var source = """
            using Prognosis;
            using Prognosis.DependencyInjection;

            class Setup
            {
                void Configure(PrognosisBuilder health)
                {
                    health.AddComposite("Application", app => { });
                }
            }
            """;

        var generated = await RunGeneratorAndGetSource(source);

        Assert.Contains("public const string Application = \"Application\";", generated);
    }

    [Fact]
    public async Task AddDelegate_StringArg_CollectedIntoHealthNames()
    {
        var source = """
            using Prognosis;
            using Prognosis.DependencyInjection;

            class Setup
            {
                void Configure(PrognosisBuilder health)
                {
                    health.AddDelegate<FakeService>("EmailProvider",
                        svc => HealthStatus.Healthy);
                }
            }
            class FakeService { }
            """;

        var generated = await RunGeneratorAndGetSource(source);

        Assert.Contains("public const string EmailProvider = \"EmailProvider\";", generated);
    }

    [Fact]
    public async Task MixedSources_AllCollected()
    {
        var source = """
            using Prognosis;
            using Prognosis.DependencyInjection;

            class Setup
            {
                void Configure(PrognosisBuilder health)
                {
                    var node = HealthNode.CreateDelegate("Database");
                    health.AddComposite("Application", app => { });
                    health.AddDelegate<FakeService>("EmailProvider",
                        svc => HealthStatus.Healthy);
                }
            }
            class FakeService { }
            """;

        var generated = await RunGeneratorAndGetSource(source);

        Assert.Contains("public const string Application = \"Application\";", generated);
        Assert.Contains("public const string Database = \"Database\";", generated);
        Assert.Contains("public const string EmailProvider = \"EmailProvider\";", generated);
    }

    // ── Helpers ──────────────────────────────────────────────────────

    private static GeneratorDriver CreateDriver(string source)
    {
        var syntaxTree = CSharpSyntaxTree.ParseText(source);

        var references = AppDomain.CurrentDomain.GetAssemblies()
            .Where(a => !a.IsDynamic && !string.IsNullOrEmpty(a.Location))
            .Select(a => MetadataReference.CreateFromFile(a.Location))
            .Cast<MetadataReference>()
            .ToList();

        // Add core Prognosis and DI assemblies.
        references.Add(MetadataReference.CreateFromFile(typeof(Prognosis.HealthNode).Assembly.Location));
        references.Add(MetadataReference.CreateFromFile(typeof(Prognosis.DependencyInjection.PrognosisBuilder).Assembly.Location));

        var compilation = CSharpCompilation.Create(
            "TestCompilation",
            [syntaxTree],
            references,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        var generator = new HealthNodeNameCollector();
        var driver = CSharpGeneratorDriver.Create(generator)
            .RunGenerators(compilation);

        return driver;
    }

    private static async Task RunGeneratorTest(
        string source,
        params (string filename, string content)[] expectedGenerated)
    {
        var test = new CSharpSourceGeneratorTest<HealthNodeNameCollector, DefaultVerifier>
        {
            TestState =
            {
                Sources = { source },
                ReferenceAssemblies = ReferenceAssemblies.Net.Net90,
                AdditionalReferences =
                {
                    MetadataReference.CreateFromFile(typeof(Prognosis.HealthNode).Assembly.Location),
                    MetadataReference.CreateFromFile(typeof(Prognosis.DependencyInjection.PrognosisBuilder).Assembly.Location),
                },
            },
        };

        foreach (var (filename, content) in expectedGenerated)
        {
            test.TestState.GeneratedSources.Add(
                (typeof(HealthNodeNameCollector), filename, content));
        }

        await test.RunAsync();
    }

    private static async Task<string> RunGeneratorAndGetSource(string source)
    {
        var driver = CreateDriver(source);
        var result = driver.GetRunResult();

        Assert.Single(result.GeneratedTrees);
        return result.GeneratedTrees[0].GetText().ToString();
    }
}
